# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(20201C)
$foreground = rgb(EBF9FD)
$color0 = rgb(464742)
$color1 = rgb(AB912F)
$color2 = rgb(43B19F)
$color3 = rgb(5197D0)
$color4 = rgb(D98D5F)
$color5 = rgb(93DA6D)
$color6 = rgb(81E0FA)
$color7 = rgb(DAEFF4)
$color8 = rgb(99A7AB)
$color9 = rgb(AB912F)
$color10 = rgb(43B19F)
$color11 = rgb(5197D0)
$color12 = rgb(D98D5F)
$color13 = rgb(93DA6D)
$color14 = rgb(81E0FA)
$color15 = rgb(DAEFF4)
