# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EBF9FD
background         #20201C
cursor             #A9D5D1

active_tab_foreground     #20201C
active_tab_background     #EBF9FD
inactive_tab_foreground   #EBF9FD
inactive_tab_background   #20201C

active_border_color   #EBF9FD
inactive_border_color #20201C
bell_border_color     #AB912F

color0      #464742
color1		#AB912F
color2		#43B19F
color3		#5197D0
color4		#D98D5F
color5		#93DA6D
color6		#81E0FA
color7		#DAEFF4
color8		#99A7AB
color9		#AB912F
color10		#43B19F
color11		#5197D0
color12		#D98D5F
color13		#93DA6D
color14		#81E0FA
color15		#DAEFF4
