
width=60%
height=60%

; anchor=center
; x-offset=0
; y-offset=0
margin-top=20%
margin-bottom=20%
margin-left=20%
margin-right=20%

corner-radius=12
border-width=3

padding-left=64
padding-right=64
padding-top=64
padding-bottom=64

; background=#1a0f14
background-color=#1a0f14dd
border-color=#ff9e64
font=JetBrainsMonoNL Nerd Font:size=12

prompt-text=󱁴:
prompt-color=#ff9e64
prompt-background=#1a0f14

; input-color=#ffd7af
; input-background=#2a171f
; text-cursor-color=#ffd7af

; placeholder-text=
; placeholder-color=#ffcba4
; placeholder-background=#2a171f
; placeholder-background-padding=8
; placeholder-background-corner-radius=10

; result-spacing=3
; default-result-color=#ffd7af
; default-result-background=#221119
; alternate-result-background=#2b1620

selection-color=#1a0f14
selection-background=#ff9e64
; selection-match-background=#f7768e
