
width=60%
height=60%

; anchor=center
; x-offset=0
; y-offset=0
margin-top=20%
margin-bottom=20%
margin-left=20%
margin-right=20%

corner-radius=24
border-width=3

padding-left=64
padding-right=64
padding-top=64
padding-bottom=64


background-color="#0C1316e0"
border-color="#6F5E53"
font=JetBrainsMonoNL Nerd Font:size=12

prompt-text=󱁴:
prompt-color="#6F5E53"
prompt-background="#0C1316e0"

selection-color="#0C1316e0"
selection-background="#6F5E53"
