
width=60%
height=60%

; anchor=center
; x-offset=0
; y-offset=0
margin-top=20%
margin-bottom=20%
margin-left=20%
margin-right=20%

corner-radius=24
border-width=3

padding-left=64
padding-right=64
padding-top=64
padding-bottom=64


background-color="#24211ce0"
border-color="#C5B8A1"
font=JetBrainsMonoNL Nerd Font:size=12

prompt-text=󱁴:
prompt-color="#C5B8A1"
prompt-background="#24211ce0"

selection-color="#24211ce0"
selection-background="#C5B8A1"
