
width=60%
height=60%

; anchor=center
; x-offset=0
; y-offset=0
margin-top=20%
margin-bottom=20%
margin-left=20%
margin-right=20%

corner-radius=24
border-width=3

padding-left=64
padding-right=64
padding-top=64
padding-bottom=64


background-color="#08070Ee0"
border-color="#6053D2"
font=JetBrainsMonoNL Nerd Font:size=12

prompt-text=󱁴:
prompt-color="#6053D2"
prompt-background="#08070Ee0"

selection-color="#08070Ee0"
selection-background="#6053D2"
